#Multi-stage YAML pipeline demo.
name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

schedules:
  - cron: "45 6 * * 4"
    branches:
      include:
        - master
    displayName: Weekly Thursday 6h45 am UTC build
    always: true

variables:
  - name: terraform_version
    value: "0.12.13"
  - name: vmImageName
    value: "ubuntu-latest"
  - name: backend_main_secret_file_id1 # secret id located in your Azure DevOps library, file used by the following cmdlet Terraform init, plan, apply and destroy
    value: "backend-main-jdld-1.json"
  - name: artifact_name
    value: "AzureDevops-Introduction"

resources:
  repositories:
    - repository: Yaml_Templates # identifier (A-Z, a-z, 0-9, and underscore)
      type: git #git refers to Azure Repos Git repos
      name: Template/template_pipeline #To refer to a repo in another project within the same organization, prefix the name with that project's name. For example, OtherProject/otherRepo.
      ref: refs/tags/0.1.0 # ref name to use, defaults to 'refs/heads/master'

trigger:
  batch: true # when a build is running, the system waits until the build is completed
  branches:
    include:
      - master
      - feature/*
      - release/*
  paths:
    include:
      - AzureDevops-Introduction/*

stages:
  - stage: Build
    jobs:
      - job: Terraform_Plan
        displayName: Terraform Plan - Publish a package if Infrastructure changes are identified
        continueOnError: false
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: DownloadSecureFile@1
            displayName: "Download secure file $(backend_main_secret_file_id1)"
            inputs:
              secureFile: $(backend_main_secret_file_id1)

          - template: terraform.yml@Yaml_Templates
            parameters:
              version: $(terraform_version)
              path: "./AzureDevops-Introduction/aks-k8s/"
              package_name: "aks-k8s"
              terraform_init: true
              terraform_plan: true
              backend_secret_file_id: $(backend_main_secret_file_id1)
              backend_file_path: "variable/backend-jdld.tfvars"
              main_secret_file_id: $(backend_main_secret_file_id1)
              main_file_path: "variable/main-jdld.tfvars"

          - publish: "./ArtifactPublishLocation" # Local path to include in the Artifact
            artifact: "$(artifact_name)"

  - stage: Deploy
    dependsOn: Build
    jobs:
      # track deployments on the environment
      - deployment: Terraform_Apply
        displayName: Terraform Apply - Resources creation
        pool:
          vmImage: $(vmImageName)
        environment: "Terraform_Apply"
        strategy:
          # default deployment strategy
          runOnce:
            deploy:
              steps:
                - template: terraform.yml@Yaml_Templates
                  parameters:
                    version: $(terraform_version)
                    artifact_path: $(Pipeline.Workspace)/$(artifact_name)
                    package_name: "aks-k8s"
                    terraform_apply: true
                    main_file_path: "variable/main-jdld.tfvars"

  - stage: Deliver
    dependsOn: Deploy
    jobs:
      # track deployments on the environment
      - deployment: Terraform_Destroy
        displayName: Terraform Destroy - Script ok, now deleting the resources
        pool:
          vmImage: $(vmImageName)
        environment: "Terraform_Destroy"
        strategy:
          # default deployment strategy
          runOnce:
            deploy:
              steps:
                - task: DownloadSecureFile@1
                  displayName: Download secure file $(backend_main_secret_file_id1)
                  inputs:
                    secureFile: $(backend_main_secret_file_id1)

                - template: terraform.yml@Yaml_Templates
                  parameters:
                    version: $(terraform_version)
                    artifact_path: $(Pipeline.Workspace)/$(artifact_name)
                    package_name: "aks-k8s"
                    terraform_destroy: true
                    main_secret_file_id: $(backend_main_secret_file_id1)
                    main_file_path: "variable/main-jdld.tfvars"
